version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ahfneto
      POSTGRES_PASSWORD: teste123
      POSTGRES_DB: gym
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: fastapi-app-1
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://ahfneto:teste123@db:5432/gym
    ports:
      - "8000:8000"
